// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xrumrjnnfjhaqnbzrrgd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhydW1yam5uZmpoYXFuYnpycmdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1MzQ3MjMsImV4cCI6MjA2MjExMDcyM30.O-ASfhLT5VMsRwjWliu9FoILY1po7ZPeb3nuFgGV044";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);